src/Entity/Actualite.php
<?php

namespace App\Entity;

use App\Repository\ActualiteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;

/**
 * @ORM\Entity(repositoryClass=ActualiteRepository::class)
 */
class Actualite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenue;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $poster_le;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="actualites")
     * @JoinColumn( onDelete="SET NULL")
     */
    private $utilisateur;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="actualite", orphanRemoval=true)
     */
    private $commentaires;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->poster_le = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenue(): ?string
    {
        return $this->contenue;
    }

    public function setContenue(string $contenue): self
    {
        $this->contenue = $contenue;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPosterLe(): ?\DateTimeInterface
    {
        return $this->poster_le;
    }

    public function setPosterLe(\DateTimeInterface $poster_le): self
    {
        $this->poster_le = $poster_le;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setActualite($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getActualite() === $this) {
                $commentaire->setActualite(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->titre;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }
}

src/Form/ActualiteType.php
<?php

namespace App\Form;

use App\Entity\Actualite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActualiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, )
            ->add('contenue', TextareaType::class)
            ->add('actif', ChoiceType::class, [
                'choices' => [
                    'Oui' => 1,
                    'Non' => 0,
                ],
            ])
            ->add('ajouter', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Actualite::class,
        ]);
    }
}

src/Controller/ActualiteController.php
<?php

namespace App\Controller;

use App\Entity\Actualite;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ActualiteController extends AbstractController
{
    /**
     * @Route("/actualite", name="actualite")
     */
    public function index(ManagerRegistry $doctrine): Response
    {
        $actualites = $doctrine->getRepository(Actualite::class)->findBy([], ['poster_le' => 'DESC']);

        return $this->render('actualite/index.html.twig', [
            'actualites' => $actualites,
        ]);
    }

    /**
     * @Route("/actualite/{id}", name="show_actualite")
     */
    public function show(Actualite $actualite, ManagerRegistry $doctrine, Request $requete): Response
    {
        $em = $doctrine->getManager();

        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($requete);
            if ($form->isSubmitted() && $form->isValid()) {
                $commentaire = $form->getData();
                $commentaire->setUtilisateur($this->getUser());
                $commentaire->setActualite($actualite);
                $commentaire->setActif(true);
    
                $em->persist($commentaire);
                $em->flush();
    
                return $this->redirectToRoute('show_actualite', [
                    'id' => $actualite->getId(),
                ]);
            }
        $commentaire_list = $actualite->getCommentaires();

        return $this->render('actualite/show.html.twig', [
            'actualite' => $actualite,
            'formCommentaire' => $form->createView(),
            'commentaire_list' => $commentaire_list,
        ]);
    }
}

templates/actualite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actualite
{% endblock %}

{% block body %}

<div class="actu-container">
	{% for actu in actualites %}
	{% if actu.actif == true %}
	<div class="carte">
		<div class="carte-container">
			<h2>
				<a href="{{ path('show_actualite', {'id': actu.id}) }}" class="text-secondary">{{ actu }}</a>
			</h2>
			<p>{{ actu.contenue }}</p>
			<small>{{ actu.utilisateur }}</small>
			<small>Poster le :
				{{ actu.posterLe | date('d-m-Y H:i:s') }}</small>
		</div>
	</div>
	{% endif %}
	{% endfor %}
</div>
{% endblock %}

templates/actualite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ actualite }}{% endblock %}

{% block body %}
<div class="actu">
    <h1>{{ actualite }}</h1>
    <small>{{ actualite.posterLe | date('d/m/Y H:i:s') }}</small>
    <p>{{ actualite.contenue }}</p>
    {% if (app.user) or (is_granted('ROLE_ADMIN')) %}
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Laisser un commentaire
    </button>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Commentaire</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ form_start(formCommentaire)}}
                        {{ form_row(formCommentaire.contenue) }}
                </div>
                <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                        {{ form_row(formCommentaire.envoyer) }}
                    {{ form_end(formCommentaire) }}
                </div>
            </div>
        </div>
    </div>
</div>
<hr>
{% include 'commentaire/commentaires.twig' %}
{% endblock %}