src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $numero;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_commande;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_total;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="commandes")
     * @JoinColumn( onDelete="SET NULL")
     */
    private $utilisateur;

    /**
     * @ORM\OneToMany(targetEntity=Panier::class, mappedBy="commande")
     */
    private $paniers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomComplet;

    /**
     * @ORM\ManyToOne(targetEntity=Adresse::class, inversedBy="commandes")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $adresseLivraison;

    /**
     * @ORM\Column(type="boolean")
     */
    private $payer;

    /**
     * @ORM\OneToOne(targetEntity=Facture::class, inversedBy="commande", cascade={"persist", "remove"})
     */
    private $facture;

    public function __construct()
    {
        $this->paniers = new ArrayCollection();
        $this->numero = $this->genererNum();
        $this->date_commande = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getPrixTotal(): ?float
    {
        return $this->prix_total;
    }

    public function setPrixTotal(float $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function genererNum()
    {
        $jour = date('Ymd');
        $time = time();

        return $jour.$time;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): self
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers[] = $panier;
            $panier->setCommande($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): self
    {
        if ($this->paniers->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getCommande() === $this) {
                $panier->setCommande(null);
            }
        }

        return $this;
    }

    public function getNomComplet(): ?string
    {
        return $this->nomComplet;
    }

    public function setNomComplet(string $nomComplet): self
    {
        $this->nomComplet = $nomComplet;

        return $this;
    }

    public function getAdresseLivraison(): ?Adresse
    {
        return $this->adresseLivraison;
    }

    public function setAdresseLivraison(?Adresse $adresseLivraison): self
    {
        $this->adresseLivraison = $adresseLivraison;

        return $this;
    }

    public function isPayer(): ?bool
    {
        return $this->payer;
    }

    public function setPayer(bool $payer): self
    {
        $this->payer = $payer;

        return $this;
    }

    public function getFacture(): ?Facture
    {
        return $this->facture;
    }

    public function setFacture(?Facture $facture): self
    {
        $this->facture = $facture;

        return $this;
    }
}

src/Controller/PaiementController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Entity\Facture;
use App\Repository\CommandeRepository;
use Doctrine\Persistence\ManagerRegistry;
use Dompdf\Dompdf;
use Dompdf\Options;
use Stripe\Checkout\Session;
use Stripe\Stripe;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PaiementController extends AbstractController
{
    /**
     * @Route("/paiement", name="paiement")
     */
    public function index(CommandeRepository $cRepo): Response
    {
        $user = $this->getUser();
        $commande = $cRepo->findByCommandeNonPayer($user->getId());
        dump($commande);
        $paniers = $commande->getPaniers();

        return $this->render('paiement/index.html.twig', [
            'commande' => $commande,
            'paniers' => $paniers,
        ]);
    }

    /**
     * @Route("/checkout", name="checkout")
     */
    public function checkout(CommandeRepository $cRepo): Response
    {
        $DOMAIN = 'http://127.0.0.1:8000/';

        $user = $this->getUser();
        $commande = $cRepo->findByCommandeNonPayer($user->getId());
        $paniers = $commande->getPaniers();
        $line_items = [];

        foreach ($paniers as $panier) {
            $line_items[] = [
                'price_data' => [
                    'currency' => 'eur',
                    'product_data' => [
                        'name' => $panier->getProduit(),
                    ],
                    'unit_amount' => $panier->getProduit()->getPrix() * 100,
                ],
                'quantity' => $panier->getQuantite(),
            ];
        }

        Stripe::setApiKey($this->getParameter('stripe_secret_key'));

        $session = Session::create([
            'customer_email' => $user->getEmail(),
            'payment_method_types' => ['card'],
            'line_items' => [
                [
                    $line_items,
                ],
            ],
            'mode' => 'payment',
            'success_url' => $DOMAIN.'success',
            'cancel_url' => $DOMAIN.'cancel',
        ]);

        // dd($session);

        return $this->redirect($session->url);
    }

    /**
     * @Route("/success", name="success_paiement")
     */
    public function successUrl(CommandeRepository $cRepo, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $user = $this->getUser();
        $commande = $cRepo->findByCommandeNonPayer($user->getId());

        // Si l'utilisateur n'a pas de commande on le redirige
        if ($user != $commande->getUtilisateur()) {
            return $this->redirectToRoute('accueil');
        }

        //Si le paiement est passer on change la valeurs du champs payer de la commande
        $commande->setPayer(true);

        // Puis une génère une facture
        $facture = new Facture();
        $facture->setNumero($facture->genererNum());
        $facture->setNom($user->getNom());
        $facture->setPrenom($user->getPrenom());
        $facture->setCommande($commande);
        $facture->setAdresse($commande->getAdresseLivraison());
        $facture->setCp($commande->getAdresseLivraison()->getCp());
        $facture->setVille($commande->getAdresseLivraison()->getVille());
        $facture->setPays($commande->getAdresseLivraison()->getPays());

        $em->persist($facture);
        $em->flush();

        return $this->render('paiement/success.html.twig', [
            'facture' => $facture,
            'commande' => $commande,
        ]);
    }

    /**
     * @Route("/cancel", name="cancel_paiement")
     */
    public function cancelUrl(): Response
    {
        return $this->render('paiement/cancel.html.twig', [
        ]);
    }

    /**
     * @Route("/facture/{id}", name="facture")
     */
    public function telechargerFacture(Commande $commande)
    {
        $options = new Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isRemoteEnabled', true);
        $options->set('defaultFont', 'courier');

        $dompdf = new Dompdf($options);

        // $html = "<img src='C:\laragon\www\Marvin\Symfony_FBDessinsNum\public\image\logo\logo_white_fbdn.png'>";

        $html = $this->renderView('paiement/facture.html.twig', [
            'sitename' => 'Test facture pdf',
            'commande' => $commande,
        ]);

        $dompdf->loadHtml($html);

        $dompdf->setPaper('A4', 'portrait');

        $dompdf->render();

        $dompdf->stream('Facture n°'.$commande->getFacture(), [
            'Attachment' => true,
        ]);

        exit(0);
    }
}

templates/paiement/cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annulation{% endblock %}

{% block body %}
<section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
</section>
{% endblock %}

templates/paiement/facture.html.twig
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <style>
        .titre-facture{
            color: #e91e63;
        }

        table{
            width: 100%;
            border-collapse: collapse;
        }

        tr, th{
            border: 1px solid #dddddd;
            text-align: center;
            padding: 0.5em;
        }

        tr:nth-child(even) {
             background-color: #dddddd;
        }

        .facture-container{
            position: relative;
            margin: 1em;
        }

        .total{
            text-align: center
        }

        .information{
            color: #e91e63;
            font-weight: bold;
        }

        .info-client{
           position: absolute;
           right: 0;
           top: 0
        }

    </style>
</head>

<body>
    <img src="" alt="Example">
    <h2 class="titre-facture">Facture</h2>
    <div>
        <small>Date de facturation : {{ commande.facture.dateFactu | date('d/m/Y') }}</small>
        <p>Numéro de la facture : {{ commande.facture.numero }}</p>
    </div>

    <div class="facture-container">
        <div class="info-boite">
            <p class="information">Information de l'entreprise</p class="information">
            <p>Fayek Bahloul Dessin Numerique</p>
            <p>10 Rue des Dessins</p>
            <p>67100, Strasbourg</p>
            <p>07 80 90 40 50</p>
            <p>fayekBahloul@dessins-num.fr</p>
        </div>

        <div class="info-client">
            <p class="information">Information du client</p class="information">
            <p>{{commande.nomComplet}}</p>
            <p>{{ commande.facture.adresse }}</p>
            <p>{{ commande.facture.cp}} {{ commande.facture.ville}}</p>
            <p>{{ app.user.email }}</p>
        </div>
    </div>

    <table class="text-danger">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Quantité</th>
            <th>Prix Unitaire</th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
            {% for panier in commande.paniers %}
            <tr>
                <td>{{ panier.produit }}</td>
                <td>{{ panier.quantite }}</td>
                <td>{{ panier.produit.prix }}€</td>
                <td>{{ panier.produit.prix * panier.quantite }}€</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th >Total commande</th>
                <td scope="row" colspan="3" class="total">{{ commande.prixTotal }}€</td>
            </tr>
        </tfoot>
    </table>
</body>

</html>

templates/paiement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement{% endblock %}

{% block body %}
<div class="adresses">
    <h2>Adresse de livraison</h2>
    <p>{{ commande.nomComplet }}</p>
    <p>{{ commande.AdresseLivraison.adresse}}</p>
    <p>{{ commande.adresseLivraison.cp}}, {{ commande.adresseLivraison.ville }}</p>
    <p>{{ commande.adresselivraison.pays }}</p>
</div>

<div class="panier">
    <h2>Votre commande</h2>
    {% for panier in paniers %}
        <p>{{ panier.produit }} X{{ panier.quantite }} | {{ panier.produit.prix }}€</p>
    {% endfor %}
    <hr>
    <p>Total de la commande : {{ commande.prixTotal }}€</p>
</div>
<form action="/checkout" method="POST">
    <button type="submit" class="btn btn-success mt-2 mb-2">Passer au paiement</button>
</form>
{% endblock %}

templates/paiement/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Succès{% endblock %}
{% block body %}
<h1>Merci pour votre commande {{app.user}}</h1>
 <li>Facture n°{{ commande.facture }} : <a href="{{ path('facture', {'id': commande.id} ) }}">Télecharger</a></li>
{% endblock %}